import json
import os
import boto3
import urllib.request
import urllib.parse
from typing import Dict, Any, Optional

# Initialize AWS clients
secretsmanager = boto3.client('secretsmanager')
bedrock_runtime = boto3.client('bedrock-runtime', region_name=os.environ.get('AWS_REGION_BEDROCK', 'us-east-1'))

def lambda_handler(event: Dict[str, Any], context: Any) -> Dict[str, Any]:
    """
    AWS Lambda handler for GitHub webhook PR reviews
    """
    try:
        # Parse the webhook payload
        body = json.loads(event.get('body', '{}'))

        # Only process pull request events
        if 'pull_request' not in body:
            return create_response(200, {'message': 'Not a pull request event'})

        action = body.get('action')

        # Only process opened and synchronize (new commits) events
        if action not in ['opened', 'synchronize']:
            return create_response(200, {'message': f'Ignoring action: {action}'})

        pull_request = body['pull_request']
        pr_number = pull_request['number']
        repo_full_name = body['repository']['full_name']
        diff_url = pull_request['diff_url']

        print(f"Processing PR #{pr_number} in {repo_full_name}")

        # Get GitHub token from Secrets Manager
        github_token = get_github_token()

        # Get PR diff
        pr_diff = get_pr_diff(diff_url, github_token)

        if not pr_diff:
            return create_response(200, {'message': 'No diff to review'})

        # Generate review using Bedrock
        review_comment = generate_review(pr_diff, pull_request)

        # Post comment to GitHub PR
        post_github_comment(repo_full_name, pr_number, review_comment, github_token)

        return create_response(200, {'message': 'Review posted successfully'})

    except Exception as e:
        print(f"Error: {str(e)}")
        return create_response(500, {'error': str(e)})


def get_github_token() -> str:
    """
    Retrieve GitHub token from AWS Secrets Manager
    """
    secret_name = os.environ['GITHUB_TOKEN_SECRET_NAME']

    try:
        response = secretsmanager.get_secret_value(SecretId=secret_name)
        secret = json.loads(response['SecretString'])
        return secret['token']
    except Exception as e:
        print(f"Error retrieving GitHub token: {str(e)}")
        raise


def get_pr_diff(diff_url: str, github_token: str) -> Optional[str]:
    """
    Fetch the PR diff from GitHub
    """
    try:
        req = urllib.request.Request(
            diff_url,
            headers={
                'Authorization': f'token {github_token}',
                'Accept': 'application/vnd.github.v3.diff'
            }
        )

        with urllib.request.urlopen(req) as response:
            return response.read().decode('utf-8')

    except Exception as e:
        print(f"Error fetching PR diff: {str(e)}")
        return None


def generate_review(pr_diff: str, pull_request: Dict[str, Any]) -> str:
    """
    Generate PR review using AWS Bedrock Claude
    """
    model_id = os.environ.get('BEDROCK_MODEL_ID', 'anthropic.claude-3-5-sonnet-20241022-v2:0')

    pr_title = pull_request.get('title', 'N/A')
    pr_description = pull_request.get('body', 'No description provided')

    prompt = f"""You are an expert code reviewer. Please review the following pull request and provide constructive feedback.

PR Title: {pr_title}

PR Description:
{pr_description}

Code Changes (diff):
```diff
{pr_diff}
```

Please provide:
1. A summary of the changes
2. Potential issues or bugs
3. Security concerns (if any)
4. Performance considerations
5. Code quality and best practices suggestions
6. Overall assessment (Approve / Request Changes / Comment)

Keep your review constructive, specific, and helpful. Focus on important issues rather than minor style preferences."""

    request_body = {
        "anthropic_version": "bedrock-2023-05-31",
        "max_tokens": 4000,
        "temperature": 0.3,
        "messages": [
            {
                "role": "user",
                "content": prompt
            }
        ]
    }

    try:
        response = bedrock_runtime.invoke_model(
            modelId=model_id,
            body=json.dumps(request_body)
        )

        response_body = json.loads(response['body'].read())
        review_text = response_body['content'][0]['text']

        # Add footer
        footer = "\n\n---\n*This review was generated by AWS Bedrock Claude via automated PR review system*"

        return review_text + footer

    except Exception as e:
        print(f"Error generating review: {str(e)}")
        return f"Error generating review: {str(e)}"


def post_github_comment(repo_full_name: str, pr_number: int, comment: str, github_token: str) -> None:
    """
    Post a comment on the GitHub PR
    """
    url = f"https://api.github.com/repos/{repo_full_name}/issues/{pr_number}/comments"

    data = json.dumps({'body': comment}).encode('utf-8')

    req = urllib.request.Request(
        url,
        data=data,
        headers={
            'Authorization': f'token {github_token}',
            'Accept': 'application/vnd.github.v3+json',
            'Content-Type': 'application/json'
        },
        method='POST'
    )

    try:
        with urllib.request.urlopen(req) as response:
            print(f"Comment posted successfully: {response.status}")
    except Exception as e:
        print(f"Error posting comment: {str(e)}")
        raise


def create_response(status_code: int, body: Dict[str, Any]) -> Dict[str, Any]:
    """
    Create API Gateway response
    """
    return {
        'statusCode': status_code,
        'headers': {
            'Content-Type': 'application/json'
        },
        'body': json.dumps(body)
    }
